

services:
  backend:
    build:
      context: .             
      dockerfile: backend/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
    deploy:
      replicas: 3

  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - nginx

  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
