version: '3.8'

services:
  # ────── BACKEND ──────
  backend:
    build:
      context: .
      dockerfile: backend/Dockerfile
    expose:
      - "5000"
    env_file:
      - .env
    depends_on:
      - mongo1
      - mongo2
      - mongo3
    # replicas: 3
    networks:
      - app-network

  # ────── FRONTEND ──────
  frontend:
    build:
      context: .
      dockerfile: frontend/Dockerfile
    ports:
      - "5173:5173"
    depends_on:
      - nginx
    networks:
      - app-network

  # ────── NGINX ──────
  nginx:
    image: nginx:alpine
    ports:
      - "80:80"
    depends_on:
      - backend
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
    networks:
      - app-network

  # ────── MONGO REPLICA SET ──────
  mongo1:
    image: mongo:6
    container_name: mongo1
    ports:
      - "27017:27017"
    command: ["mongod", "--replSet", "rs0"]
    restart: always
    networks:
      - app-network

  mongo2:
    image: mongo:6
    container_name: mongo2
    ports:
      - "27018:27017"
    command: ["mongod", "--replSet", "rs0"]
    restart: always
    networks:
      - app-network

  mongo3:
    image: mongo:6
    container_name: mongo3
    ports:
      - "27019:27017"
    command: ["mongod", "--replSet", "rs0"]
    restart: always
    networks:
      - app-network

networks:
  app-network:
    driver: bridge
